# Generated by Django 5.1.6 on 2025-03-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_message_likes_alter_message_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
